import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-50 m-0">
          <div className="min-h-screen max-w-4xl mx-auto py-12 px-4">
            {children}
          </div>

          <footer className="text-center py-4 text-sm text-gray-500">
          &copy; Trap Stars for ZUS 2025
        </footer>
        </div>
      </body>
    </html>
  );
}
