import type { Metadata } from "next";
import "./globals.css";
import ContrastToggle from "@/components/constrast-toggle";
import { EmaChat } from "@/components/chat/ema-chat";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function PreloadContrast() {
  // runs before paint; no React hooks here
  return (
    <script
      dangerouslySetInnerHTML={{
        __html: `
(function(){
  try {
    var k = 'contrast-mode';
    var m = localStorage.getItem(k);
    if (m === 'hc-white' || m === 'hc-yellow') {
      document.addEventListener('DOMContentLoaded', function(){
        document.body.classList.add(m);
      });
    }
  } catch(e) {}
})();
        `.trim(),
      }}
    />
  );
}



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pl">
      <head>
        <PreloadContrast />
      </head>
      <body className="antialiased">
        <ContrastToggle />
        <div className="min-h-screen bg-zus-bg text-zus-text transition-colors duration-300">
          {children}
        </div>
        <EmaChat />
      </body>
    </html>
  );
}